/* Automatically generated nanopb header */
/* Generated by nanopb-1.0.0-dev */

#ifndef PB_INPUT_PB_H_INCLUDED
#define PB_INPUT_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _Input {
    pb_callback_t s;
} Input;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define Input_init_default                       {{{NULL}, NULL}}
#define Input_init_zero                          {{{NULL}, NULL}}

/* Field tags (for use in manual encoding/decoding) */
#define Input_s_tag                              1

/* Struct field encoding specification for nanopb */
#define Input_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   s,                 1)
#define Input_CALLBACK pb_default_field_callback
#define Input_DEFAULT NULL

extern const pb_msgdesc_t Input_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define Input_fields &Input_msg

/* Maximum encoded size of messages (where known) */
/* Input_size depends on runtime parameters */

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
