# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mystruct.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0emystruct.proto\"c\n\x08MyStruct\x12\n\n\x02id\x18\x01 \x01(\x05\x12\r\n\x05score\x18\x02 \x01(\x02\x12\x0c\n\x04name\x18\x03 \x01(\t\x12\x0e\n\x06values\x18\x04 \x03(\x01\x12\x1e\n\x03sub\x18\x05 \x01(\x0b\x32\x11.AnonymousStruct1\".\n\x10\x41nonymousStruct1\x12\x0c\n\x04\x63ode\x18\x01 \x01(\x05\x12\x0c\n\x04\x64\x65sc\x18\x02 \x01(\tb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'mystruct_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _MYSTRUCT._serialized_start=18
  _MYSTRUCT._serialized_end=117
  _ANONYMOUSSTRUCT1._serialized_start=119
  _ANONYMOUSSTRUCT1._serialized_end=165
# @@protoc_insertion_point(module_scope)
